version: 2
jobs:
  build:
    docker:
      - image: lifealicious/programmer-dot-sh:latest
        auth:
          username: lifealicious
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A first hello"
