version: 2
jobs:
  build:
    working_directory: /programmer-dot-sh
    docker:
      - image: docker:18.09.5-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update py-pip
            pip install docker-compose
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/programmer-dot-sh.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/programmer-dot-sh.tar | true
      - run:
          name: Build Application Docker image
          command: |
            docker build --cache-from=programmer-dot-sh -t programmer-dot-sh .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/programmer-dot-sh.tar programmer-dot-sh
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/programmer-dot-sh.tar
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose -f ./docker-compose.test.yml up
      - run:
          name: Push Application Docker image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}"
              docker tag programmer-dot-sh "lifealicious/programmer-dot-sh:latest"
              docker push "lifealicious/programmer-dot-sh:latest"
            fi

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH to Digital Ocean Droplet
          command: |
            ssh -o StrictHostKeyChecking=no -v "${DROPLET_USER}@${DROPLET_IP}" "./deploy_project.sh"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
